# Generated by Django 5.0.3 on 2024-04-16 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='body',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
    ]
