# Generated by Django 5.0.3 on 2024-04-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0003_alter_mahsulot_soni'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mahsulot',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
